name = "TwoPhasesPressure"
uuid = "bb123139-b47c-4342-a6ae-61ccdd2293f9"
authors = ["tduretz <duretz@uni-frankfurt.de>"]
version = "0.1.0"

[deps]
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
